#!/usr/bin/python

from os import listdir, getcwd
from os.path import isfile, join
import re
import sys
import datetime

#def human_time(*args, **kwargs):
#    secs  = float(datetime.timedelta(*args, **kwargs).total_seconds())
#    units = [("day", 86400), ("hour", 3600), ("minute", 60), ("second", 1)]
#    parts = []
#    for unit, mul in units:
#        if secs / mul >= 1 or mul == 1:
#            if mul > 1:
#                n = int(math.floor(secs / mul))
#                secs -= n * mul
#            else:
#                n = secs if secs != int(secs) else int(secs)
#            parts.append("%s %s%s" % (n, unit, "" if n == 1 else "s"))
#    return ", ".join(parts)


cwd = getcwd()
dirs = reversed(sorted([f for f in listdir(cwd) if re.match("^201", f)]))

def num_failed_jobs(dir):
  filenames = listdir(join(cwd, d))

  failed = 0

  for f in filenames:
    full = join(join(cwd, d), f)
    failure_lines = [line for line in open(full) if "exit signals: Killed" in line]
    failed += len(failure_lines)

  return failed
  

print "     epoch       files failed  summary"

for d in dirs:
  md_filename = join(join(cwd, d), "METADATA")
  num_files = len(listdir(join(cwd, d)))

  summary = "-"

#  ago = human_time(seconds=3721)

  if isfile(md_filename):
    summary = open(md_filename).read().replace('\n', ' ')

  failed = num_failed_jobs(d)
    
  line = "%s %5d %5d   %s" % (d, num_files, failed, summary)

  print line
